#!/usr/bin/env node
/**
 * Extract recipe candidates from an XLSX and generate:
 * - excel-items.json
 * - insert-recipes.sql
 *
 * Usage:
 *   node scripts/extract-recipes.js <input.xlsx> [output-dir]
 * Example:
 *   node scripts/extract-recipes.js "./docs/important-data-reference/Gbol Comandas.xlsx" "./supabase/migrations/generated"
 */

const fs = require("fs");
const path = require("path");
const XLSX = require("xlsx");

function usage() {
  console.error("Usage: node scripts/extract-recipes.js <input.xlsx> [output-dir]");
  process.exit(1);
}

function sqlEscape(value) {
  return String(value).replace(/'/g, "''");
}

function main() {
  const inputPath = process.argv[2];
  const outputDir = process.argv[3] || path.join("supabase", "migrations", "generated");
  const headerIdx = 6;

  if (!inputPath) usage();

  const absInput = path.isAbsolute(inputPath) ? inputPath : path.join(process.cwd(), inputPath);
  if (!fs.existsSync(absInput)) {
    console.error(`Input file not found: ${inputPath}`);
    process.exit(1);
  }

  const wb = XLSX.readFile(absInput);
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "" });

  const unique = new Map();
  for (let i = headerIdx + 1; i < rows.length; i += 1) {
    const row = rows[i];
    if (!row || !row[0] || !row[1]) continue;
    const codigo = String(row[0]).trim();
    const articulo = String(row[1]).trim();
    if (!codigo || !articulo) continue;
    if (codigo.includes("Noche") || codigo.includes("Fecha")) continue;
    if (articulo.includes("Noche") || articulo.includes("Fecha")) continue;
    if (codigo.length >= 10) continue;
    unique.set(`${codigo}::${articulo}`, { codigo, articulo });
  }

  const items = Array.from(unique.values());

  const sqlLines = [];
  sqlLines.push("-- SQL generated by scripts/extract-recipes.js");
  sqlLines.push("-- Review before executing in production.");
  sqlLines.push("");
  for (const item of items) {
    sqlLines.push(
      `INSERT INTO master_recipes (name, external_id) VALUES ('${sqlEscape(item.articulo)}', '${sqlEscape(
        item.codigo
      )}') ON CONFLICT DO NOTHING;`
    );
  }
  sqlLines.push("");

  const absOut = path.isAbsolute(outputDir) ? outputDir : path.join(process.cwd(), outputDir);
  fs.mkdirSync(absOut, { recursive: true });

  const jsonPath = path.join(absOut, "excel-items.json");
  const sqlPath = path.join(absOut, "insert-recipes.sql");

  fs.writeFileSync(jsonPath, JSON.stringify(items, null, 2), "utf8");
  fs.writeFileSync(sqlPath, sqlLines.join("\n"), "utf8");

  console.log(`Items extraidos: ${items.length}`);
  console.log(`JSON: ${path.relative(process.cwd(), jsonPath).replace(/\\/g, "/")}`);
  console.log(`SQL: ${path.relative(process.cwd(), sqlPath).replace(/\\/g, "/")}`);
}

main();
